--傅孝来, 2018-2-9

drop TABLE TTS_SCLTXXCJ_NOTIFICATION_V2;

CREATE TABLE "TTS_SCLTXXCJ_NOTIFICATION_V2" (
"ID" VARCHAR2(64 BYTE) NOT NULL ,
"FROM_ID" VARCHAR2(64 BYTE) NULL ,
"FROM_NAME" VARCHAR2(64 BYTE) NULL ,
"TO_ID" VARCHAR2(64 BYTE) NULL ,
"TO_NAME" VARCHAR2(64 BYTE) NULL ,
"TITLE" VARCHAR2(200 BYTE) NULL ,
"CONTENT" VARCHAR2(1000 BYTE) NULL ,
"CREATE_BY" VARCHAR2(128 BYTE) NULL ,
"CREATE_TIME" DATE NULL ,
"UPDATE_BY" VARCHAR2(128 BYTE) NULL ,
"UPDATE_TIME" DATE NULL ,
"DEL_FLAG" VARCHAR2(2 BYTE) NULL ,
"ISREAD" VARCHAR2(2 BYTE) NULL ,
PRIMARY KEY ("ID")
)
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)

TABLESPACE "USERS"
LOGGING
NOCOMPRESS
NOCACHE
;

ALTER TABLE "TTS_SCLTXXCJ_NOTIFICATION_V2" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_NOTIFICATION_V2" ADD CHECK ("ID" IS NOT NULL);
COMMENT ON COLUMN "TTS_SCLTXXCJ_NOTIFICATION_V2"."ID" IS '唯一标识';
COMMENT ON COLUMN "TTS_SCLTXXCJ_NOTIFICATION_V2"."FROM_ID" IS '来源ID';
COMMENT ON COLUMN "TTS_SCLTXXCJ_NOTIFICATION_V2"."FROM_NAME" IS '来源名称';
COMMENT ON COLUMN "TTS_SCLTXXCJ_NOTIFICATION_V2"."TO_ID" IS '去向ID';
COMMENT ON COLUMN "TTS_SCLTXXCJ_NOTIFICATION_V2"."TO_NAME" IS '去向名称';
COMMENT ON COLUMN "TTS_SCLTXXCJ_NOTIFICATION_V2"."TITLE" IS '标题';
COMMENT ON COLUMN "TTS_SCLTXXCJ_NOTIFICATION_V2"."CONTENT" IS '内容';
COMMENT ON COLUMN "TTS_SCLTXXCJ_NOTIFICATION_V2"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "TTS_SCLTXXCJ_NOTIFICATION_V2"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "TTS_SCLTXXCJ_NOTIFICATION_V2"."UPDATE_BY" IS '修改人';
COMMENT ON COLUMN "TTS_SCLTXXCJ_NOTIFICATION_V2"."UPDATE_TIME" IS '修改时间';
COMMENT ON COLUMN "TTS_SCLTXXCJ_NOTIFICATION_V2"."DEL_FLAG" IS '删除标识';
COMMENT ON COLUMN "TTS_SCLTXXCJ_NOTIFICATION_V2"."ISREAD" IS '是否阅读';

-- ----------------------------
-- Checks structure for table TTS_SCLTXXCJ_NOTIFICATION_V2
-- ----------------------------
ALTER TABLE "TTS_SCLTXXCJ_NOTIFICATION_V2" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_NOTIFICATION_V2" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table TTS_SCLTXXCJ_NOTIFICATION_V2
-- ----------------------------
ALTER TABLE "TTS_SCLTXXCJ_NOTIFICATION_V2" ADD PRIMARY KEY ("ID");
alter table T_SCLTXXCJ_BASE_V2 add DICT_NAME  varchar(10);



--郑秋成  2018-2-9
------------------------------------------------------------------------
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD UNIQUE ("ACCOUNT");

ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD UNIQUE ("ACCOUNT");
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD UNIQUE ("INFO_UNIQUE");

-- ----------------------------
-- Checks structure for table TTS_SCLTXXCJ_REGISTER_V2
-- ----------------------------
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("ACCOUNT" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("IDCODE" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("ENTITY_SCALE" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("ENTITY_TYPE" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("ENTITY_PROPERTY" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("ENTITY_INDUSTRY" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("ADDRESS" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("AREA" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("LONGITUDE" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("LATITUDE" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("LEGAL_NAME" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("LEGAL_IDNUMBER" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("LEGAL_PHONE" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("LEGAL_IMAGES" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("CONTACT_NAME" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("CONTACT_PHONE" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("CONTACT_EMAIL" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("APPROVE_STATUS" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("ENTITY_IDCODE" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("DEL_FLAG" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("INFO_UNIQUE" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("ENTITY_SCALE_NAME" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("ENTITY_TYPE_NAME" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("ENTITY_PROPERTY_NAME" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("ENTITY_INDUSTRY_NAME" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("POSITIVE_IDCARDEIMG" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("NEGATIVE_IDCARDIMG" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("HAND_IDCARDIMG" IS NOT NULL);
ALTER TABLE "TTS_SCLTXXCJ_REGISTER_V2" ADD CHECK ("REAL_NAME" IS NOT NULL);

ALTER TABLE TTS_SCLTXXCJ_USER_V2 ADD WHETHER_PASSWORD VARCHAR2(200);
ALTER TABLE TTS_SCLTXXCJ_USER_V2 ADD CHECK_EDIT_PASSWORD VARCHAR2(200);

