-- ----------------------------
-- Table structure for TTS_SCLTXXCJ_NOTIFICATION_V2
-- ----------------------------
--谭礼，2018-03-08，修改表TTS_SCLTXXCJ_NOTIFICATION_V2中FROM_NAME和TO_NAME的字段长度为255，原因为存储通知消息时企业名称较长会报值不够的错误。
DROP TABLE "GJZSPT"."TTS_SCLTXXCJ_NOTIFICATION_V2";
CREATE TABLE "GJZSPT"."TTS_SCLTXXCJ_NOTIFICATION_V2" (
"ID" VARCHAR2(64 BYTE) NOT NULL ,
"FROM_ID" VARCHAR2(64 BYTE) NULL ,
"FROM_NAME" VARCHAR2(255 BYTE) NULL ,
"TO_ID" VARCHAR2(64 BYTE) NULL ,
"TO_NAME" VARCHAR2(255 BYTE) NULL ,
"TITLE" VARCHAR2(200 BYTE) NULL ,
"CONTENT" VARCHAR2(1000 BYTE) NULL ,
"CREATE_BY" VARCHAR2(128 BYTE) NULL ,
"CREATE_TIME" DATE NULL ,
"UPDATE_BY" VARCHAR2(128 BYTE) NULL ,
"UPDATE_TIME" DATE NULL ,
"DEL_FLAG" VARCHAR2(2 BYTE) NULL ,
"ISREAD" VARCHAR2(2 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "GJZSPT"."TTS_SCLTXXCJ_NOTIFICATION_V2"."ID" IS '唯一标识';
COMMENT ON COLUMN "GJZSPT"."TTS_SCLTXXCJ_NOTIFICATION_V2"."FROM_ID" IS '来源ID';
COMMENT ON COLUMN "GJZSPT"."TTS_SCLTXXCJ_NOTIFICATION_V2"."FROM_NAME" IS '来源名称';
COMMENT ON COLUMN "GJZSPT"."TTS_SCLTXXCJ_NOTIFICATION_V2"."TO_ID" IS '去向ID';
COMMENT ON COLUMN "GJZSPT"."TTS_SCLTXXCJ_NOTIFICATION_V2"."TO_NAME" IS '去向名称';
COMMENT ON COLUMN "GJZSPT"."TTS_SCLTXXCJ_NOTIFICATION_V2"."TITLE" IS '标题';
COMMENT ON COLUMN "GJZSPT"."TTS_SCLTXXCJ_NOTIFICATION_V2"."CONTENT" IS '内容';
COMMENT ON COLUMN "GJZSPT"."TTS_SCLTXXCJ_NOTIFICATION_V2"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "GJZSPT"."TTS_SCLTXXCJ_NOTIFICATION_V2"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "GJZSPT"."TTS_SCLTXXCJ_NOTIFICATION_V2"."UPDATE_BY" IS '修改人';
COMMENT ON COLUMN "GJZSPT"."TTS_SCLTXXCJ_NOTIFICATION_V2"."UPDATE_TIME" IS '修改时间';
COMMENT ON COLUMN "GJZSPT"."TTS_SCLTXXCJ_NOTIFICATION_V2"."DEL_FLAG" IS '删除标识';
COMMENT ON COLUMN "GJZSPT"."TTS_SCLTXXCJ_NOTIFICATION_V2"."ISREAD" IS '是否阅读';

-- ----------------------------
-- Indexes structure for table TTS_SCLTXXCJ_NOTIFICATION_V2
-- ----------------------------

-- ----------------------------
-- Checks structure for table TTS_SCLTXXCJ_NOTIFICATION_V2
-- ----------------------------
ALTER TABLE "GJZSPT"."TTS_SCLTXXCJ_NOTIFICATION_V2" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "GJZSPT"."TTS_SCLTXXCJ_NOTIFICATION_V2" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "GJZSPT"."TTS_SCLTXXCJ_NOTIFICATION_V2" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table TTS_SCLTXXCJ_NOTIFICATION_V2
-- ----------------------------
ALTER TABLE "GJZSPT"."TTS_SCLTXXCJ_NOTIFICATION_V2" ADD PRIMARY KEY ("ID");
